### PR TITLE
Feature/componentize oauth2

### PR DESCRIPTION
**Pull request by raymondfeng**
/to @bajtos or @ritch

### CODE REVIEW

**Comment by bajtos** [comment]
The change itself LGTM, but I don't understand why you don't move the middleware registration to `middleware.json`, as we did in strong-gateway?

**Comment by raymondfeng** [comment]
@bajtos Do we already support `middleware.json` inside a component?

**Comment by raymondfeng** [comment]
I'll defer the `middleware.json` refactoring as we already do so in `strong-gateway`.

**Comment by bajtos** [comment]
:+1: 

It turned out it does not make sense to register complex components like oauth2 via `middleware.json`, so I implemented `component-config.json` that allows registration of components via `function(app, options)`.

**Pull request merged**
